[install]
alias = "i"
mode = "afk"
iterations = 1
auto_push = true

[spec]
alias = "s"
mode = "interactive"
iterations = 1
auto_push = false

[build]
alias = "b"
mode = "interactive"
iterations = 30
auto_push = true

[verify]
alias = "v"
mode = "afk"
iterations = 30
auto_push = true

[test-plan]
mode = "afk"
iterations = 30
auto_push = true

[test]
mode = "afk"
iterations = 30
auto_push = true

[issues-log]
mode = "interactive"
iterations = 1
auto_push = false

[doc]
mode = "interactive"
iterations = 1
auto_push = false
