description = "'It is incarnated' | Give flesh to the specs"
alias = "ic"

[[iters]]
name = "spec-to-issues"
prompt = "incarnatur-0-spec-to-issues"
mode = "afk"
iterations = 50


[[iters]]
name = "spec-to-issues-final-pass"
prompt = "incarnatur-1-spec-to-issues-final-pass"
mode = "afk"
iterations = 1


[[iters]]
name = "build"
prompt = "incarnatur-2-build"
mode = "afk"
iterations = 500


# [[iters]]
# name = "flesh-audit"
# prompt = "incarnatur-3-flesh-audit"
# mode = "afk"
# iterations = 50
# produces = "flesh-audit-presentation"


# [[iters]]
# name = "present"
# prompt = "incarnatur-4-present"
# mode = "interactive"
# consumes = ["flesh-audit-presentation"]
