description = "'It is incarnated' | Give flesh to the specs"
alias = "ic"
auto_push = true

[[iter]]
name = "spec-to-issues"
prompt = "incarnatur-0-spec-to-issues.md"
mode = "afk"
iterations = 50


[[iter]]
name = "spec-to-issues-final-pass"
prompt = "incarnatur-1-spec-to-issues-final-pass.md"
mode = "afk"
iterations = 1


[[iter]]
name = "build"
prompt = "incarnatur-2-build.md"
mode = "afk"
iterations = 500


# [[iter]]
# name = "flesh-audit"
# prompt = "incarnatur-3-flesh-audit"
# mode = "afk"
# iterations = 50
# produces = "flesh-audit-presentation"


# [[iter]]
# name = "present"
# prompt = "incarnatur-4-present"
# mode = "interactive"
# consumes = ["flesh-audit-presentation"]
