description = "'It prays' | Entreat that the specs may be changed"
alias = "pc"
auto_push = true


[[iter]]
name = "gather-refine-and-create"
prompt = "gather-refine-and-create.md"
mode = "interactive"

[[iter]]
name = "harden"
prompt = "spec-harden.md"
mode = "interactive"
produces = "discuss-and-interview-summary"
iterations = 25

